import { useState, useEffect } from "react";
import jsPDF from "jspdf";
import "jspdf-autotable";
import "./StudentLogin.css";

function StudentLogin() {
  const [token, setToken] = useState(localStorage.getItem('studentToken'));
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [studentInfo, setStudentInfo] = useState(null);
  const [results, setResults] = useState([]);

  useEffect(() => {
    if (token) fetchMyResults();
  }, [token]);

  const fetchMyResults = async () => {
    const res = await fetch("/api/my-results", { headers: { Authorization: `Bearer ${token}` } });
    if(res.ok) {
      const data = await res.json();
      setResults(data.results);
      setStudentInfo(data.student);
    } else {
      localStorage.removeItem('studentToken');
      setToken(null);
    }
  };

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const res = await fetch("/api/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username: phone, password })
      });
      const data = await res.json();
      if (res.ok && data.role === 'student') {
        localStorage.setItem("studentToken", data.token);
        setToken(data.token);
      } else {
        alert(data.error || "Login Failed. Try switching the password to your DOB.");
      }
    } catch(err) {
      alert("Network Error");
    }
  };

  const logout = () => {
    localStorage.removeItem("studentToken");
    setToken(null);
  };

  const downloadMarklist = (result) => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(0, 109, 119); // Teal
    doc.text("BAYANUL ULOOM DARS KUNNATH", 105, 20, null, null, "center");
    
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Student Marklist", 105, 30, null, null, "center");

    doc.setFontSize(12);
    doc.text(`Student Name: ${studentInfo?.studentName || 'N/A'}`, 20, 50);
    doc.text(`Exam Name: ${result.examName}`, 20, 60);
    doc.text(`Published On: ${new Date(result.publishedDate).toLocaleDateString()}`, 20, 70);

    doc.autoTable({
      startY: 80,
      head: [['Particulars', 'Score']],
      body: [
        ['Total Marks', result.totalMarks],
        ['Final Grade', result.grade]
      ],
      headStyles: { fillColor: [0, 109, 119] },
      theme: 'grid'
    });

    doc.setFontSize(10);
    doc.text("Generated by AL BAYAN KUNNATH digital ecosystem", 105, 280, null, null, "center");
    doc.save(`${studentInfo?.studentName}_${result.examName}_Marklist.pdf`);
  };

  if (!token) {
    return (
      <section className="student-login-page py-5 d-flex align-items-center justify-content-center" style={{ minHeight: '80vh' }}>
        <div className="container px-4">
          <div className="row justify-content-center">
            <div className="col-md-6 col-lg-5">
              <div className="card login-card border-0 shadow-lg position-relative overflow-hidden glass-card p-4 rounded-4">
                <div className="text-center mb-5">
                  <div className="login-logo-wrapper mb-4">
                    <img src="/logo.png" alt="Dars Logo" width="80" height="80" className="rounded-circle shadow" />
                  </div>
                  <h2 className="login-title fw-bold mb-2" style={{color: '#006d77'}}>STUDENT LOGIN</h2>
                  <p className="text-muted small">Access your dashboard & marklists</p>
                </div>
                
                <form onSubmit={handleLogin} className="login-form">
                  <div className="mb-4 text-start">
                    <label className="form-label text-muted small px-1 fw-bold">Phone / Username</label>
                    <input type="text" className="form-control p-3 bg-light" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Registerd mobile number" required />
                  </div>
                  <div className="mb-4 text-start">
                    <label className="form-label text-muted small px-1 fw-bold">Password (DOB)</label>
                    <input type="password" className="form-control p-3 bg-light" value={password} onChange={e=>setPassword(e.target.value)} placeholder="YYYY-MM-DD or as entered" required />
                  </div>
                  <button type="submit" className="btn btn-teal-primary w-100 py-3 fw-bold rounded shadow-sm mt-3">PROCEED TO DASHBOARD</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section className="student-dashboard container py-5" style={{fontFamily: 'Inter, sans-serif'}}>
      <div className="d-flex justify-content-between align-items-center mb-5 pb-3 border-bottom border-secondary">
        <div>
          <h2 className="fw-bold mb-1" style={{color: '#006d77'}}>Welcome, {studentInfo?.studentName}</h2>
          <p className="text-muted mb-0">Student ID: {studentInfo?._id?.slice(-6).toUpperCase()}</p>
        </div>
        <button onClick={logout} className="btn btn-outline-danger fw-bold rounded-pill px-4">Sign Out</button>
      </div>

      <h3 className="mb-4 fw-bold">Official Results & Marklists</h3>
      
      {results.length === 0 ? (
        <div className="alert alert-info border-0 shadow-sm p-4 rounded-4 text-center">
          <h4 className="fw-bold mb-2">No Results Yet!</h4>
          <p className="mb-0">Your exam results have not been published by the administration yet. Check back later.</p>
        </div>
      ) : (
        <div className="row g-4">
          {results.map(res => (
            <div key={res._id} className="col-md-6 col-lg-4">
              <div className="card h-100 border-0 shadow-sm rounded-4 overflow-hidden">
                <div className="bg-teal-primary text-white p-3 text-center text-capitalize">
                  <h5 className="mb-0 fw-bold">{res.examName}</h5>
                </div>
                <div className="card-body p-4 text-center bg-light">
                  <p className="text-muted small mb-2">Total Score</p>
                  <h2 className="display-4 fw-bold mb-3">{res.totalMarks}</h2>
                  <span className="badge bg-success fs-5 px-4 py-2 rounded-pill shadow-sm">Grade: {res.grade}</span>
                  <div className="mt-4 pt-3 border-top border-light">
                    <p className="small text-muted mb-3">Published: {new Date(res.publishedDate).toLocaleDateString()}</p>
                    <button onClick={() => downloadMarklist(res)} className="btn btn-outline-teal w-100 fw-bold py-2">
                      ⬇ Download Marklist
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

export default StudentLogin;
