import { useState, useEffect } from "react";
import jsPDF from "jspdf";
import "jspdf-autotable";
import "./StudentLogin.css";

function StudentLogin() {
  const [token, setToken] = useState(localStorage.getItem('studentToken'));
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [studentInfo, setStudentInfo] = useState(null);
  const [results, setResults] = useState([]);
  
  // Profile & Tab States
  const [activeTab, setActiveTab] = useState("results"); // 'results', 'profile', or 'notices'
  const [uploadingDoc, setUploadingDoc] = useState(false);
  const [notifications, setNotifications] = useState([]);
  const [tempBio, setTempBio] = useState("");

  useEffect(() => {
    if (token) {
      fetchMyResults();
      fetchNotifications();
    }
  }, [token]);

  const fetchNotifications = async () => {
    const res = await fetch("/api/notifications");
    if(res.ok) setNotifications(await res.json());
  };

  const fetchMyResults = async () => {
    const res = await fetch("/api/my-results", { headers: { Authorization: `Bearer ${token}` } });
    if(res.ok) {
      const data = await res.json();
      setResults(data.results);
      setStudentInfo(data.student);
      setTempBio(data.student?.bio || "");
    } else {
      localStorage.removeItem('studentToken');
      setToken(null);
    }
  };

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const res = await fetch("/api/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username: phone, password })
      });
      const data = await res.json();
      if (res.ok && data.role === 'student') {
        localStorage.setItem("studentToken", data.token);
        setToken(data.token);
      } else {
        alert(data.error || "Login Failed. Try switching the password to your DOB.");
      }
    } catch(err) {
      alert("Network Error");
    }
  };

  const logout = () => {
    localStorage.removeItem("studentToken");
    setToken(null);
  };

  const handleDocumentUpload = async (e, type) => {
    const file = e.target.files[0];
    if (!file) return;
    
    setUploadingDoc(true);
    const formData = new FormData();
    formData.append("file", file);

    try {
      const uploadRes = await fetch("/api/upload", { method: "POST", body: formData });
      const uploadData = await uploadRes.json();
      if (!uploadRes.ok) throw new Error(uploadData.error);

      // Save to profile
      const updatePayload = {};
      if (type === 'aadhar') updatePayload.aadharFile = uploadData.url;
      if (type === 'sslc') updatePayload.sslcFile = uploadData.url;
      if (type === 'profile') updatePayload.profilePhoto = uploadData.url;
      if (type === 'birthCert') updatePayload.birthCertFile = uploadData.url;
      if (type === 'tc') updatePayload.tcFile = uploadData.url;
      if (type === 'marklist') updatePayload.marklistFile = uploadData.url;

      const updateRes = await fetch("/api/my-profile", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify(updatePayload)
      });
      
      if(updateRes.ok) {
        alert("Profile document uploaded successfully!");
        fetchMyResults(); // Refresh student data
      }
    } catch(err) {
      alert("Failed to upload document. Please try again.");
    } finally {
      setUploadingDoc(false);
    }
  };

  const handleProfileUpdate = async (updateData) => {
    try {
      const res = await fetch("/api/my-profile", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify(updateData)
      });
      if(res.ok) {
        alert("Profile updated!");
        fetchMyResults();
      }
    } catch(err) { alert("Update failed"); }
  };

  const downloadMarklist = (result) => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(0, 109, 119); // Teal
    doc.text("BAYANUL ULOOM DARS KUNNATH", 105, 20, null, null, "center");
    
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Student Marklist", 105, 30, null, null, "center");

    doc.setFontSize(12);
    doc.text(`Student Name: ${studentInfo?.studentName || 'N/A'}`, 20, 50);
    doc.text(`Exam Name: ${result.examName}`, 20, 60);
    doc.text(`Published On: ${new Date(result.publishedDate).toLocaleDateString()}`, 20, 70);

    doc.autoTable({
      startY: 80,
      head: [['Particulars', 'Score']],
      body: [
        ['Total Marks', result.totalMarks],
        ['Final Grade', result.grade]
      ],
      headStyles: { fillColor: [0, 109, 119] },
      theme: 'grid'
    });

    doc.setFontSize(10);
    doc.text("Generated by AL BAYAN KUNNATH digital ecosystem", 105, 280, null, null, "center");
    doc.save(`${studentInfo?.studentName}_${result.examName}_Marklist.pdf`);
  };

  if (!token) {
    return (
      <section className="student-login-page py-5 d-flex align-items-center justify-content-center" style={{ minHeight: '80vh' }}>
        <div className="container px-4">
          <div className="row justify-content-center">
            <div className="col-md-6 col-lg-5">
              <div className="card login-card border-0 shadow-lg position-relative overflow-hidden glass-card p-4 rounded-4">
                <div className="text-center mb-5">
                  <div className="login-logo-wrapper mb-4">
                    <img src="/logo.png" alt="Dars Logo" width="80" height="80" className="rounded-circle shadow" />
                  </div>
                  <h2 className="login-title fw-bold mb-2" style={{color: '#006d77'}}>STUDENT LOGIN</h2>
                  <p className="text-muted small">Access your dashboard & marklists</p>
                </div>
                
                <form onSubmit={handleLogin} className="login-form">
                  <div className="mb-4 text-start">
                    <label className="form-label text-muted small px-1 fw-bold">Phone / Username</label>
                    <input type="text" className="form-control p-3 bg-light" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Registerd mobile number" required />
                  </div>
                  <div className="mb-4 text-start">
                    <label className="form-label text-muted small px-1 fw-bold">Password (DOB)</label>
                    <input type="password" className="form-control p-3 bg-light" value={password} onChange={e=>setPassword(e.target.value)} placeholder="YYYY-MM-DD or as entered" required />
                  </div>
                  <button type="submit" className="btn btn-teal-primary w-100 py-3 fw-bold rounded shadow-sm mt-3">PROCEED TO DASHBOARD</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section className="student-dashboard container py-5" style={{fontFamily: 'Inter, sans-serif'}}>
      <div className="d-flex justify-content-between align-items-center mb-5 pb-3 border-bottom border-secondary">
        <div>
          <h2 className="fw-bold mb-1" style={{color: '#006d77'}}>
            Welcome, {studentInfo?.studentName}
            <span className={`ms-3 badge fs-6 ${studentInfo?.status === 'approved' ? 'bg-success' : studentInfo?.status === 'rejected' ? 'bg-danger' : 'bg-warning text-dark'}`}>
              {studentInfo?.status?.toUpperCase() || 'PENDING APPROVAL'}
            </span>
          </h2>
          <p className="text-muted mb-0">Student ID: {studentInfo?._id?.slice(-6).toUpperCase()}</p>
        </div>
        <button onClick={logout} className="btn btn-outline-danger fw-bold rounded-pill px-4">Sign Out</button>
      </div>

      <div className="d-flex border-bottom mb-4">
        <button className={`btn rounded-0 px-4 py-3 fw-bold ${activeTab === 'results' ? 'btn-teal-primary shadow-sm' : 'text-muted'}`} onClick={() => setActiveTab('results')}>🏆 My Results</button>
        <button className={`btn rounded-0 px-4 py-3 fw-bold ${activeTab === 'profile' ? 'active bg-teal-primary text-white shadow-sm' : 'text-muted'}`} onClick={() => setActiveTab('profile')}>👤 My Profile</button>
        <button className={`btn rounded-0 px-4 py-3 fw-bold ${activeTab === 'notices' ? 'btn-teal-primary shadow-sm' : 'text-muted'}`} onClick={() => setActiveTab('notices')}>📢 Announcements ({notifications.length})</button>
      </div>

      {activeTab === 'profile' && (
        <div className="row g-4">
          <div className="col-md-4">
            <div className="card shadow-sm border-0 rounded-4 p-4 text-center mb-4">
              <div className="mb-4 position-relative d-inline-block">
                <img 
                  src={studentInfo?.profilePhoto || "/logo.png"} 
                  alt="Profile" 
                  className="rounded-circle shadow" 
                  style={{width: '150px', height: '150px', objectFit: 'cover'}} 
                />
                <label className="btn btn-sm btn-teal-primary position-absolute bottom-0 end-0 rounded-circle" disabled={uploadingDoc} style={{width: '40px', height: '40px', lineHeight: '25px'}}>
                  {uploadingDoc ? '...' : '✏️'}
                  <input type="file" accept="image/*" className="d-none" onChange={(e) => handleDocumentUpload(e, 'profile')} />
                </label>
              </div>
              <h4 className="fw-bold">{studentInfo?.studentName}</h4>
              <p className="text-muted mb-0">DOB: {studentInfo?.dob}</p>
              <p className="text-muted">Phone: {studentInfo?.phone}</p>
            </div>

            <div className="card shadow-sm border-0 rounded-4 p-4">
              <h5 className="fw-bold border-bottom pb-2 mb-3">Quick Actions</h5>
              <div className="mb-3">
                <label className="fw-bold small d-block mb-1">Update About Me</label>
                <textarea className="form-control bg-light mb-2 small" rows="3" value={tempBio} onChange={e=>setTempBio(e.target.value)} />
                <button className="btn btn-sm btn-teal-primary w-100" onClick={() => handleProfileUpdate({ bio: tempBio })}>Save Bio</button>
              </div>
            </div>
          </div>
          
          <div className="col-md-8">
            <div className="card shadow-sm border-0 rounded-4 p-4 mb-4">
              <h4 className="fw-bold border-bottom pb-3 mb-4 text-teal">Detailed Information</h4>
              <div className="row g-3">
                {[
                  { label: "Father's Name", value: studentInfo?.fatherName, key: "fatherName" },
                  { label: "Mother's Name", value: studentInfo?.motherName, key: "motherName" },
                  { label: "Guardian Contact", value: studentInfo?.guardianPhone, key: "guardianPhone" },
                  { label: "Email Address", value: studentInfo?.email, key: "email" },
                  { label: "Blood Group", value: studentInfo?.bloodGroup, key: "bloodGroup" },
                  { label: "Native Place", value: studentInfo?.place, key: "place" }
                ].map(item => (
                  <div className="col-md-6" key={item.key}>
                    <label className="small fw-bold text-muted">{item.label}</label>
                    <div className="d-flex gap-2">
                       <input 
                         className="form-control form-control-sm bg-light" 
                         defaultValue={item.value || ""} 
                         onBlur={(e) => {
                           if(e.target.value !== item.value) handleProfileUpdate({ [item.key]: e.target.value });
                         }}
                       />
                    </div>
                  </div>
                ))}
                <div className="col-12 mt-3">
                  <label className="small fw-bold text-muted">Residential Address</label>
                  <textarea 
                    className="form-control bg-light" 
                    rows="2" 
                    defaultValue={studentInfo?.address || ""}
                    onBlur={(e) => {
                      if(e.target.value !== studentInfo?.address) handleProfileUpdate({ address: e.target.value });
                    }}
                  />
                </div>
              </div>
            </div>

            <div className="card shadow-sm border-0 rounded-4 p-4">
              <h4 className="fw-bold border-bottom pb-3 mb-4 text-teal">Mandatory Documents</h4>
              <div className="row g-4">
                {[
                  { label: "Aadhar Card", key: "aadhar", file: studentInfo?.aadharFile },
                  { label: "SSLC / Education Log", key: "sslc", file: studentInfo?.sslcFile },
                  { label: "Birth Certificate", key: "birthCert", file: studentInfo?.birthCertFile },
                  { label: "Transfer Certificate (TC)", key: "tc", file: studentInfo?.tcFile },
                  { label: "Last Exam Marklist", key: "marklist", file: studentInfo?.marklistFile }
                ].map(doc => (
                  <div className="col-md-6" key={doc.key}>
                    <div className="border rounded-3 p-3 bg-light h-100">
                      <label className="fw-bold d-block mb-2 small">{doc.label}</label>
                      {doc.file ? (
                        <div className="d-flex align-items-center gap-2">
                          <span className="badge bg-success small">✔️ OK</span>
                          <a href={doc.file} target="_blank" rel="noreferrer" className="btn btn-xs btn-link text-teal p-0">View</a>
                          <label className="btn btn-link text-secondary p-0 small ms-auto mb-0">
                            Re-upload <input type="file" className="d-none" onChange={e => handleDocumentUpload(e, doc.key)} />
                          </label>
                        </div>
                      ) : (
                        <div>
                          <input type="file" className="form-control form-control-sm" onChange={e => handleDocumentUpload(e, doc.key)} disabled={uploadingDoc} />
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {activeTab === 'notices' && (
        <div className="row justify-content-center">
          <div className="col-lg-8">
            <h3 className="mb-4 fw-bold">Campus Announcements</h3>
            <div className="list-group shadow-sm border-0">
              {notifications.map(n => (
                <div key={n._id} className={`list-group-item border-0 shadow-sm mb-3 rounded-4 p-4 ${n.type === 'urgent' ? 'bg-light-danger border-start border-danger border-5' : 'bg-white border-start border-teal border-5'}`}>
                  <div className="d-flex justify-content-between align-items-start mb-2">
                    <h5 className="fw-bold mb-0 text-teal">{n.title}</h5>
                    <span className="badge bg-light text-dark border small">{new Date(n.createdAt).toLocaleDateString()}</span>
                  </div>
                  <p className="mb-0 text-secondary">{n.message}</p>
                </div>
              ))}
              {notifications.length === 0 && (
                <div className="text-center py-5 text-muted">
                  <span className="display-4 d-block mb-3">📭</span>
                  <p>No new announcements at this time.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {activeTab === 'results' && (
        <>
          <h3 className="mb-4 fw-bold">Official Results & Marklists</h3>
          {results.length === 0 ? (
            <div className="alert alert-info border-0 shadow-sm p-4 rounded-4 text-center">
              <h4 className="fw-bold mb-2">No Results Yet!</h4>
              <p className="mb-0">Your exam results have not been published by the administration yet. Check back later.</p>
            </div>
          ) : (
            <div className="row g-4">
              {results.map(res => (
                <div key={res._id} className="col-md-6 col-lg-4">
                  <div className="card h-100 border-0 shadow-sm rounded-4 overflow-hidden">
                    <div className="bg-teal-primary text-white p-3 text-center text-capitalize">
                      <h5 className="mb-0 fw-bold">{res.examName}</h5>
                    </div>
                    <div className="card-body p-4 text-center bg-light">
                      <p className="text-muted small mb-2">Total Score</p>
                      <h2 className="display-4 fw-bold mb-3">{res.totalMarks}</h2>
                      <span className="badge bg-success fs-5 px-4 py-2 rounded-pill shadow-sm">Grade: {res.grade}</span>
                      <div className="mt-4 pt-3 border-top border-light">
                        <p className="small text-muted mb-3">Published: {new Date(res.publishedDate).toLocaleDateString()}</p>
                        <button onClick={() => downloadMarklist(res)} className="btn btn-outline-teal w-100 fw-bold py-2">
                          ⬇ Download Marklist
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </>
      )}
    </section>
  );
}

export default StudentLogin;
